name: CI Build with Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CI build and test

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: SonarCloud RollbaCommon
      run: SonarCloud/build-wrapper-macosx-x86/build-wrapper-macosx-x86 --out-dir sonar_build_wrapper_output xcodebuild -workspace RollbarSDK.xcworkspace -scheme RollbarCommon clean build
    
    - name: Build RollbarCommon (SwiftPM)
      working-directory: RollbarCommon
      run: swift build -v
    - name: Unit Test RollbarCommon (SwiftPM)
      working-directory: RollbarCommon
      run: swift test -v -c release
      
    - name: Build RollbarDeploys (SwiftPM)
      working-directory: RollbarDeploys
      run: swift build -v
    - name: Unit Test RollbarDeploys (SwiftPM)
      working-directory: RollbarDeploys
      run: swift test -v -c release

    - name: Build RollbarNotifier (SwiftPM)
      working-directory: RollbarNotifier
      run: swift build -v
    - name: Unit Test RollbarNotifier (SwiftPM)
      working-directory: RollbarNotifier
      run: swift test -v -c release

    - name: Build RollbarKSCrash (SwiftPM)
      working-directory: RollbarKSCrash
      run: swift build -v
    - name: Unit Test RollbarKSCrash (SwiftPM)
      working-directory: RollbarKSCrash
      run: swift test -v -c release


    - name: Build with Xcode
      run: xcodebuild -workspace RollbarSDK.xcworkspace -scheme iosAppObjC build
    - name: Unit Test with Xcode
      run: xcodebuild -workspace RollbarSDK test
