name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: CI RollbarCommon
      run: cd RollbarCommon
    - name: Build
      run: swift build -v
    - name: Unit Test
      run: swift test -v
    - name: Back to root
      run: cd ..
      
    - name: CI RollbarDeploys
      run: cd RollbarDeploys
    - name: Build
      run: swift build -v
    - name: Unit Test
      run: swift test -v
    - name: Back to root
      run: cd ..
      
    #- name: Build
    #  run: swift build -v
    #- name: Run tests
    #  run: swift test -v
